name: Monthly Portfolio Allocation

on:
  schedule:
    # Esegue lo script alle 00:00 del primo giorno di ogni mese
    - cron: '0 0 17 * *'
  workflow_dispatch: # Permette di avviarlo manualmente per test

env:
  GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }} 

jobs:
  build:
    runs-on: ubuntu-latest

    # Permessi necessari per scrivere nel repository
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pandas openpyxl numpy

    - name: Run script
      run: python src/vwce/compute_portfolio_allocation.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add *.xlsx *.csv

        # Esegue il commit solo se ci sono cambiamenti, evitando errori se i file sono identici
        git commit -m "Auto-update portfolio allocation $(date +'%Y-%m-%d')" || exit 0
        git push